name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Remove .git folder before deploy
        run: rm -rf .git

      - name: Copy Files to AWS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "."
          target: "~/toilet-exchange-bot"
          
      - name: SSH and restart bot
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/toilet-exchange-bot
            sudo chown -R ec2-user:ec2-user .
            if [ ! -d ".venv" ]; then
              python3.11 -m venv .venv
            fi
            
            source .venv/bin/activate
            
            pip install -r requirements.txt
            
            sudo systemctl daemon-reload
            sudo systemctl restart toilet-exchange
            sudo systemctl status toilet-exchange --no-pager -l
